var worldMap=[
  [
    'BBB        ',
    'B1BBBBBBBBB',
    'B2       OB',
    'BBBBBBBBBBB',
  ],
  [
    'BBBBBBBBBBBB',
    'BO         B',
    'BBBBBBB    B',
    'B2      B  B',
    'B1        BB',
    'BBBBBBBBBBBB',
  ],
  [
    'BBBBBBBBB',
    'BB      B',
    'B2      B',
    'B1 BXXB O',
    'BBBBBBBBB',
  ],
  [
    'BBBBBBBBBBBXXXXXXXXXBB',
    'B                   BB',
    'B  BB               OB',
    'B  BB      BIBBIBBIBBB',
    'B          BBBBBBBBBBB',
    'B2     IIXXXXXBBBBBBBB',
    'B1     BXXBBBBBBBBBBBB',
    'BBBBBBIBBBBBBBBBBBBBBB',
  ],
  [
    'B        BBB',
    'B  B      OB',
    'B  BBB  BBBB',
    'BI          ',
    'BB          ',
    'BBIX BBBX   ',
    'B2        I ',
    'B1        B ',
    'BBBBBBBBIIB ',
  ],
  [
    'BBBBBBBBBBBB',
    'B     1    B',
    'B     2    B',
    'B BBBBBBBB B',
    'B          B',
    'BBBXB  BXBBB',
    'B      BBBBB',
    'B  BBBBBBBBB',
    'B          B',
    'B          B',
    'B     BX   B',
    'BIXXXIBX   B',
    'BX         B',
    'B          B',
    'B  X       B',
    'B  XIBBBXXIB',
    'B         OB',
    'BBBBBBBBBBBB',
  ],
  [
    'BBBBBBBBBBBBBBBBBBB',
    'B1       BO       B',
    'BBBRRRLLRBB       B',
    'B   L    B  B     B',
    'B   R    B        B',
    'BLLRRRRRRB    I   B',
    'B        B    BLLLB',
    'B        BRRBIRRRRB',
    'B RR XX  B        B',
    'BIXXIRRLLBILLLLB  B',
    'BO       BXXXXXB 2B',
    'BBBBBBBBBBBBBXBBIBB',
  ],
  [
    'BB  BB                        X X                                   ',
    'B1   L                        X                                     ',
    'B2   L               XXX      X     III                             ',
    'BB  BB  R R L        XII                                            ',
    '    X   R L R                   IXXIII                              ',
    '        B       BBB    BBB      X         BBB                       ',
    '      B          BBB  IXB     I X          OB                       ',
    '    B          I       XX     X        BBBBBB                       ',
    '                            I X                                     ',
    '                            X                                       ',
    '                            X                                       ',
  ],
  [
    'BBBBBBBBBBBBBXXXBBB',
    'B  U  X     L   UOB',
    'B2 X  D    DL     B',
    'BBBBBBBBBRLBBBBXXXB',
    'BU  X   UU  R     B',
    'B1X D   X   R   DOB',
    'BBBBBBBBBBBBBXXXBBB',
  ],
  [
    '   BB                                   ',
    'B1 UU               XXXX                ',
    'B2    DD            B  B D         D  BB',
    'BB       X     II   D  U  R    L      OB',
    '      IIXXXBB  UU   B  B  RXXR   L  BBBB',
    '                    BXXX  LXXL   R    OB',
    '                          L    R      BB',
    '                          U        U    ',
  ],
  [
    'BXXXXXXXXXXXXXXXXXXXXXXXXXXB',
    'B2                    5    B',
    'BD            5    4      OB',
    'BBBBXBBXBBXBBBBXXXXBBXXXBBBB',
    'B1            5    4      OB',
    'BU                    5    B',
    'BXXXXXXXXXXXXXXXXXXXXXXXXXXB',
  ],
  [
    'BBBBBBBBB',
    'B 51B25 B',
    'B BBBBB B',
    'B   B   B',
    'B   B   B',
    'BX  B  XB',
    'B   B   B',
    'B   B   B',
    'B XXBXX B',
    'B   B   B',
    'B   B   B',
    'BX  B  XB',
    'BX  B  XB',
    'BXX B XXB',
    'B   B   B',
    'B   B   B',
    'B  OBO  B',
    'BBBBBBBBB',
  ],
  [
    'BBBBBBBBBBBBBBBBBBB',
    'B                 O',
    'B         5       B',
    'B                 B',
    'B       BXXXBBI   B',
    'B    I      4     B',
    'BBB               B',
    'B2BI              B',
    'B13  B  BBIIBXXXXXB',
    'BBBBBBXBBBBBBBBBBBB',
  ],
  [
    '                                              ',
    '                                              ',
    '                                              ',
    '                                              ',
    'B15   3            BXXXB                B     ',
    'B25   3            U  3 D4              D     ',
    'BBB           DD     D3 4  5        4   O     ',
    ' B     4       BBB   B    BBBBXXXBBBB   B     ',
    '       4  UU    B      U                      ',
    '      XIIX             B              U       ',
    '      XXXX                                    ',
    '                                              ',
    '                                              ',
  ],
  [
    '   BBBXB           BXBBB   ',
    '   BO XB           BX OB   ',
    '   BB  B           B  BB   ',
    '    B  B           B  B    ',
    '    BX B           B XB    ',
    '    B  B           B  B    ',
    '    B  B  BBBBBBB  B  B    ',
    '    B XB  B     B  BX B    ',
    '    BU B  L     R  B UB    ',
    '    B555  L     R  555B    ',
    '    BBBB  BB 2 BB  BBBB    ',
    '      B   BBB1BBB   B      ',
    '          BBBBBBB          ',
  ],
  [
    'XXXXXXXXXXXXXXXXX',
    'X               X',
    'X               X',
    'X               X',
    'X               X',
    'X               X',
    'X       U       X',
    'X   1        2  X',
    'X   BBBBBBBBBB  X',
    'X               X',
    'X               X',
    'X               X',
    'X               X',
    'X               X',
    'XXXXXXXXXXXXXXXXX',
    '                 ',
  ],
  [],
];